### ISSUE TITLE
Could not find a declaration file for module 'pick-random'

### ISSUE THREAD

**Issue by KhannaAbhinav** [sindresorhus/pick-random#7]
Could not find a declaration file for module 'pick-random'. 'D:/git/random-selector-action/node_modules/pick-random/index.js' implicitly has an 'any' type.
  Try `npm install @types/pick-random` if it exists or add a new declaration (.d.ts) file containing `declare module 'pick-random';`

**Comment by sindresorhus** [comment]
There's no TypeScript definition for this project yet. PR welcome. Should follow: https://github.com/sindresorhus/typescript-definition-style-guide
